### ISSUE TITLE
`Eq Complex` instance is not transitive

### ISSUE THREAD

**Issue by hdgarrood** [matthieubulte/purescript-complex#2]
I'm not aware of any way so far that this might cause a problem in real code, but the `Eq Complex` instance does not obey the transitive law of the `Eq` class. It's also a little surprising, as I would expect the `Eq Complex` instance to use the underlying `Eq` instance. I think it would be better to use the underlying `Eq` instance, but if not, this should probably at least be documented.

**Comment by matthieubulte** [comment]
You're right, I should document this behavior.

Do yiu have any idea how we could implement a correct Eq instance while avoiding the incorrectness of floating point arithmetic?

**Comment by hdgarrood** [comment]
I would use the underlying `Eq` instance:

```
eq (Complex r i) (Complex r' i') = r == r' && i == i'
```

If anyone wants approximate equality, then they write a function for it easily enough. And I think that if approximate equality is being used, it would be better if it were explicit.

Of course, you then have the same problem as `Number` that `0.1 + 0.2 /= 0.3`. To address this, perhaps you could parameterize `Complex` for a type to be used as the underlying number? For example, the current `Complex` would become `Complex Number`; and then people could switch out the type for something a little more reliable if they want; `Complex Rational`, perhaps. The instances would then be `instance (Ring a) => Semiring (Complex a) where [...]` and so on.

**Comment by matthieubulte** [comment]
Parametrizing the underlying Number was actually planned, but I'm a bit busy studying right now... I guess I can do it over the weekens though.

**Comment by hdgarrood** [comment]
oh sure, please don't feel pressured to do it, it's not like I need this for anything. If I did I would have sent a PR :)

**Comment by matthieubulte** [comment]
Well, I tried playing around with using a type parameter for the underlying number, but it seems that we're lacking something like the Haskell's [Floating](https://hackage.haskell.org/package/base-4.8.1.0/docs/Prelude.html#t:Floating) typeclass. I'm not sure though if we want to copy Haskell's number hierarchy :/

Any input on that?

**Comment by hdgarrood** [comment]
Oh of course, yeah. Hm. I'm not sure. Might be worth raising on `prelude`? I want to say "use a power series!" - that should be enough to define `cos` and `sin` and possibly `atan2` too with only a `Num` constraint - but that might be prohibitively slow and/or unworkable for other reasons...

**Comment by hdgarrood** [comment]
Alternatively I suppose you could just make the polar representation only work on `Complex Number` for now until there is a generalized `sin` and so on?
